version: '2'
services:
    insatplatform-app:
        image: insatplatform
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://insatplatform-mysql:3306/insatplatform?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=insatplatform-elasticsearch:9300
        ports:
            - 8080:8080
    insatplatform-mysql:
        extends:
            file: mysql.yml
            service: insatplatform-mysql
    insatplatform-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: insatplatform-elasticsearch
